name: wbs_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  http: ^1.1.0
  
  json_annotation: ^4.8.1
  
  table_calendar: ^3.0.9
  
  shared_preferences: ^2.2.2
  
  sqflite: ^2.3.0
  path: ^1.8.3
  
  google_sign_in: ^6.1.5
  
  url_launcher: ^6.2.2
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  
  flutter_local_notifications: ^17.2.3
  
  timezone: ^0.9.4
  
  provider: ^6.1.2

  # AdMob (Google Mobile Ads) - 나중에 사용하기 위해 주석 처리
  # google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  
  generate: true
